image:
  file: .gitpod.Dockerfile
tasks:
  - name: Install Go Libraries
    command: sh ./scripts/install-go-libs.sh
  - name: Set up Mongo
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 27017
    onOpen: open-preview
    visibility: private
