tasks:
  - name: Environment variables
    env:
      GOOGLE_APPLICATION_CREDENTIAL: /workspace/test-monGO/golang-test-6a3ef-firebase-adminsdk-qft99-eb4bf4138e.json
    command: 
      go get -u github.com/gorilla/mux
ports:
  - port: 3000
    onOpen: open-preview
