image:
  file: .gitpod.Dockerfile
tasks:
  - name: Set up Mongo
    # env:
    #   GOOGLE_APPLICATION_CREDENTIAL: /workspace/test-monGO/golang-test-6a3ef-firebase-adminsdk-qft99-eb4bf4138e.json
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
    # sh ./scripts/install-go-libs.sh
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 27017
    onOpen: open-preview
    visibility: private
